### ISSUE TITLE
Create MacOS VMs for testing

### ISSUE THREAD

**Issue by jkarni** [garnix-io/nix-tool-installer#7]
The first test should check that install on an empty system works.

**Comment by soenkehahn** [comment]
We should check what testing infrastructure the DeterminateSystems installer has. At least for inspiration.

**Comment by jfroche** [comment]
Determinate is using this: https://github.com/DeterminateSystems/macos-ephemeral to test their installer.
They are using physical hardware and reboot and reset the darwin machine after each CI run.

**Comment by jfroche** [comment]
I also looked at https://github.com/MatthewCroughan/NixThePlanet/blob/master/makeDarwinImage/default.nix which has some idea in common with what we did to run darwin in a VM here https://github.com/garnix-io/nix-tool-installer/pull/10 
It has nice hooks to setup the image but expect is failing to install the machine here.
